implement new chat bubble and remove unnecessary dependencies
timothykevin/rn-gifted-chat pull request #2
Opened 2024-07-18 08:31 UTC by riannu

- remove react-native-vector-icons dependencies because its unused
- implement transparent chat bubble 
- align chat to left
- implement basic reactions button
- size adjustment on several icons

2024-07-18 09:26 UTC, timothykevin requested changes

2024-07-18 09:26 UTC, timothykevin commented on app/components/Message.tsx
> +        <Image
cba pake `<Actions ...><Image .../></Actions>` aja biar ada press effect nya.

2024-07-18 09:26 UTC, timothykevin commented on app/index.tsx
> +  <View style={{ marginLeft: 8, marginBottom: 11 }}>
Pake `<Actions />`

2024-07-18 09:26 UTC, timothykevin commented on app/index.tsx
> +const renderCustomView = (props) => {
ini buat di mana ya? Kayak nya ga dipake

2024-07-22 04:06 UTC, riannu commented on app/index.tsx
> +const renderCustomView = (props) => {
otw hapus ya

2024-07-22 04:07 UTC, riannu commented on app/index.tsx
> +const renderCustomView = (props) => {
eh dah dihapus

2024-07-22 04:24 UTC, riannu commented on app/components/Message.tsx
> +        <Image
hmm, dasarnya ini sama saja sih. ada press effectnya jg

2024-07-22 04:28 UTC, riannu commented on app/components/Message.tsx
> +        <Image
enakan pake touchable sih. gk perlu dependencies luar. atau karena ada fitur lain ?

2024-07-22 06:49 UTC, timothykevin approved these changes

2024-07-22 06:50 UTC, merged